# 配置文件版本
version: "3"


# 管理的服务
services:

    mysql:
        image: mysql:${MYSQL_VERSION}
        container_name: mysql_${MYSQL_VERSION}
        ports:
            - ${REAL_MYSQL_PORT}:3306
        volumes:
            - ${MYSQL_DIR}/data:/var/lib/mysql:rw
            - ${MYSQL_CONF}:/etc/mysql/my.cnf:ro
            - ${MYSQL_DIR}/logs:/logs:rw
        environment:
            TZ: Asia/Shanghai
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_ROOT_HOST: ${MYSQL_ROOT_HOST}
        logging:
            driver: "json-file"
            options:
                max-size: "200m"
                max-file: "3"
        restart: always


    redis:
        image: redis:${REDIS_VERSION}
        container_name: redis_${REDIS_VERSION}
        ports:
            - ${REAL_REDIS_PORT}:6379
        volumes:
            - ${REDIS_DIR}/data:/data:rw
            - ${REDIS_CONF}:/etc/redis/redis.conf:ro
            - ${REDIS_DIR}/logs:/logs:rw
        logging:
            driver: "json-file"
            options:
                max-size: "200m"
                max-file: "3"
        restart: always
        command: ["redis-server", "/etc/redis/redis.conf"]


    es:
        image: elasticsearch:${ES_VERSION}
        container_name: es_${ES_VERSION}
        privileged: true
        user: root
        ports:
            - ${REAL_ES_HTTP_PORT}:9200
            - ${REAL_ES_TCP_PORT}:9300
        volumes:
            - ${ES_DIR}/data:/usr/share/elasticsearch/data:rw
            - ${ES_CONF}:/usr/share/elasticsearch/config/elasticsearch.yml:ro
            - ${ES_DIR}/logs:/usr/share/elasticsearch/logs:rw
        logging:
            driver: "json-file"
            options:
                max-size: "200m"
                max-file: "3"
        restart: always


    es_head:
        image: mobz/elasticsearch-head:${ES_HEAD_VERSION}
        container_name: es_head_${ES_HEAD_VERSION}
        ports:
            - ${REAL_ES_HEAD_PORT}:9100
        volumes:
            - ${ES_DIR}/logs:/logs
        logging:
            driver: "json-file"
            options:
                max-size: "200m"
                max-file: "3"
        restart: always

