# 配置文件版本
version: "3"


# 管理的服务
services:

    mysql:
        image: mysql:${MYSQL_VERSION:-5.7}
        hostname: mysql
        ports:
            - ${HOST_MYSQL_PORT:-3306}:3306
        volumes:
            - dbs-mysql:/var/lib/mysql:rw
            - ${HOST_MYSQL_CONF}:/etc/mysql/my.cnf:ro
            - ${HOST_LOG_DIR:-/var/log/dbs}/mysql:/var/log/mysql:rw
        environment:
            TZ: Asia/Shanghai
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-123456}
            MYSQL_ROOT_HOST: ${MYSQL_ROOT_HOST:-localhost}
        entrypoint:
            - /bin/bash
            - -c
            - |
                chmod a+w /var/log/mysql
                docker-entrypoint.sh mysqld
        logging:
            driver: "json-file"
            options:
                max-size: "200m"
                max-file: "3"
        restart: always
        networks:
            - front

    redis:
        image: redis:${REDIS_VERSION:-5.0.12}
        hostname: redis
        ports:
            - ${HOST_REDIS_PORT:-6379}:6379
        volumes:
            - dbs-redis:/data:rw
            - ${HOST_REDIS_CONF}:/etc/redis/redis.conf:ro
            - ${HOST_LOG_DIR:-/var/log/dbs}/redis:/logs:rw
        environment:
            TZ: Asia/Shanghai
        logging:
            driver: "json-file"
            options:
                max-size: "200m"
                max-file: "3"
        restart: always
        command: 
            - /bin/bash
            - -c
            - |
                redis-server /etc/redis/redis.conf
        networks:
            - front

    es:
        image: elasticsearch:${ES_VERSION:-6.6.2}
        hostname: es
        ports:
            - ${HOST_ES_HTTP_PORT:-9200}:9200
            - ${HOST_ES_TCP_PORT:-9300}:9300
        volumes:
            - dbs-es:/usr/share/elasticsearch/data:rw
            - ${HOST_ES_CONF}:/usr/share/elasticsearch/config/elasticsearch.yml:ro
            - ${HOST_LOG_DIR:-/var/log/dbs}/es:/usr/share/elasticsearch/logs:rw
        environment:
            TZ: Asia/Shanghai
        entrypoint:
            - /bin/bash
            - -c
            - |
                chmod a+w /usr/share/elasticsearch/logs
                /usr/local/bin/docker-entrypoint.sh eswrapper
        logging:
            driver: "json-file"
            options:
                max-size: "200m"
                max-file: "3"
        restart: always
        networks:
            - front

    es_head:
        image: mobz/elasticsearch-head:${ES_HEAD_VERSION:-5}
        hostname: es_head
        ports:
            - ${HOST_ES_HEAD_PORT:-9100}:9100
        # volumes:
        #     - ${HOST_LOG_DIR:-/var/log/dbs}/es_head:/logs:rw
        environment:
            TZ: Asia/Shanghai
        logging:
            driver: "json-file"
            options:
                max-size: "200m"
                max-file: "3"
        restart: always
        networks:
            - front

    mongo:
        image: mongo:${MONGO_VERSION:-4.4.5}
        hostname: mongo
        ports:
            - ${HOST_MONGO_PORT:-27017}:27017
        volumes:
            - dbs-mongo:/data/db:rw
            - ${HOST_LOG_DIR:-/var/log/dbs}/mongo:/var/log/mongodb:rw
        environment:
            TIME_ZONE: Asia/Shanghai
            MONGO_INITDB_DATABASE: testDB
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
        entrypoint:
            - /bin/bash
            - -c
            - |
                chmod a+w /var/log/mongodb
                docker-entrypoint.sh mongod -logpath=/var/log/mongodb/mongod.log -logRotate=reopen -logappend
        logging:
            driver: "json-file"
            options:
                max-size: "200m"
                max-file: "3"
        restart: always
        networks:
            - front

    rabbitmq:
        image: rabbitmq:${RABBITMQ_VERSION:-3.8.16-management}
        hostname: rabbitmq
        ports:
            - ${HOST_RABBITMQ_PORT:-5672}:5672
            - ${HOST_RABBITMQ_ADMIN_PORT:-15672}:15672
        volumes:
            - dbs-rabbitmq:/var/lib/rabbitmq:rw
            - ${HOST_LOG_DIR:-/var/log/dbs}/rabbitmq:/var/log/rabbitmq/log:rw
        environment:
            TIME_ZONE: Asia/Shanghai
            RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
        entrypoint:
            - /bin/bash
            - -c
            - |
                chmod a+w /var/log/rabbitmq/log
                docker-entrypoint.sh rabbitmq-server
        logging:
            driver: "json-file"
            options:
                max-size: "200m"
                max-file: "3"
        restart: always
        networks:
            - front


networks:
    front:
        ipam:
            driver: default


volumes:
    dbs-mysql: {}
    dbs-redis: {}
    dbs-es: {}
    dbs-mongo: {}
    dbs-rabbitmq: {}
