# 配置文件版本
version: "3"


# 管理的服务
services:

    mysql:
        image: mysql:${MYSQL_VERSION:-5.7}
        container_name: mysql_${MYSQL_VERSION:-5.7}
        ports:
            - ${REAL_MYSQL_PORT:-3306}:3306
        volumes:
            - dbs-mysql:/var/lib/mysql:rw
            - ${MYSQL_CONF}:/etc/mysql/my.cnf:ro
            - ${LOG_DIR:-/var/log/dbs}/mysql:/logs:rw
        environment:
            TZ: Asia/Shanghai
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-123456}
            MYSQL_ROOT_HOST: ${MYSQL_ROOT_HOST:-localhost}
        logging:
            driver: "json-file"
            options:
                max-size: "200m"
                max-file: "3"
        restart: always
        networks:
            - dbs

    redis:
        image: redis:${REDIS_VERSION:-5.0.12}
        container_name: redis_${REDIS_VERSION:-5.0.12}
        ports:
            - ${REAL_REDIS_PORT:-6379}:6379
        volumes:
            - dbs-redis:/data:rw
            - ${REDIS_CONF}:/etc/redis/redis.conf:ro
            - ${LOG_DIR:-/var/log/dbs}/redis:/logs:rw
        environment:
            TZ: Asia/Shanghai
        logging:
            driver: "json-file"
            options:
                max-size: "200m"
                max-file: "3"
        restart: always
        command: ["redis-server", "/etc/redis/redis.conf"]
        networks:
            - dbs

    es:
        image: elasticsearch:${ES_VERSION:-6.6.2}
        container_name: es_${ES_VERSION:-6.6.2}
        privileged: true
        user: root
        ports:
            - ${REAL_ES_HTTP_PORT:-9200}:9200
            - ${REAL_ES_TCP_PORT:-9300}:9300
        volumes:
            - dbs-es:/usr/share/elasticsearch/data:rw
            - ${ES_CONF}:/usr/share/elasticsearch/config/elasticsearch.yml:ro
            - ${LOG_DIR:-/var/log/dbs}/es:/usr/share/elasticsearch/logs:rw
        environment:
            TZ: Asia/Shanghai
        logging:
            driver: "json-file"
            options:
                max-size: "200m"
                max-file: "3"
        restart: always
        networks:
            - dbs

    es_head:
        image: mobz/elasticsearch-head:${ES_HEAD_VERSION:-5}
        container_name: es_head_${ES_HEAD_VERSION:-5}
        ports:
            - ${REAL_ES_HEAD_PORT:-9100}:9100
        volumes:
            - ${LOG_DIR:-/var/log/dbs}/es_head:/logs
        environment:
            TZ: Asia/Shanghai
        logging:
            driver: "json-file"
            options:
                max-size: "200m"
                max-file: "3"
        restart: always
        networks:
            - dbs

    mongo:
        image: mongo:${MONGO_VERSION:-4.4.5}
        container_name: mongo_${MONGO_VERSION:-4.4.5}
        ports:
            - ${REAL_MONGO_PORT:-27017}:27017
        volumes:
            - dbs-mongo:/data/db:rw
            - ${LOG_DIR:-/var/log/dbs}/mongo:/data/logs:rw
        environment:
            TIME_ZONE: Asia/Shanghai
            MONGO_INITDB_DATABASE: testDB
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
        logging:
            driver: "json-file"
            options:
                max-size: "200m"
                max-file: "3"
        restart: always
        networks:
            - dbs

    rabbitmq:
        image: rabbitmq:${RABBITMQ_VERSION:-3.8.16-management}
        container_name: rabbitmq_${RABBITMQ_VERSION:-3.8.16-management}
        ports:
            - ${REAL_RABBITMQ_PORT:-5672}:5672
            - ${REAL_RABBITMQ_ADMIN_PORT:-15672}:15672
        volumes:
            - dbs-rabbitmq:/var/lib/rabbitmq:rw
            - ${LOG_DIR:-/var/log/dbs}/rabbitmq:/var/log/rabbitmq/log:rw
        environment:
            TIME_ZONE: Asia/Shanghai
            RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
        logging:
            driver: "json-file"
            options:
                max-size: "200m"
                max-file: "3"
        restart: always
        networks:
            - dbs


networks:
    dbs:
        ipam:
            driver: default


volumes:
    dbs-mysql: {}
    dbs-redis: {}
    dbs-es: {}
    dbs-mongo: {}
    dbs-rabbitmq: {}
